package org.veri.be.domain.comment.model

/**
 * Comment ID Value Object
 *
 * v2.1: Type-safe ID wrapper with validation
 * - No placeholder() - requires value > 0
 * - ID is generated by JPA, domain only uses restored values
 */
@JvmInline
value class CommentId(val value: Long) {
    init {
        require(value > 0) { "Invalid CommentId: $value (must be positive)" }
    }

    companion object {
        /**
         * Restore CommentId from persisted value
         * @param value ID from database (must be positive)
         * @return Valid CommentId instance
         */
        fun of(value: Long): CommentId {
            return CommentId(value)
        }
    }
}
